### PR TITLE
add support for elan 0C1A

### PR DESCRIPTION
**Pull request by mikey0000**

### CODE REVIEW

**Comment by mikey0000** [comment]
seem to be getting cases where the device isn't being closed properly which stops fprint-demo from working as it can no longer open the device. Any clues where I should start looking?

**Comment by iafilatov** [comment]
Please see if the latest commit in `elan` works for your device.

**Comment by mikey0000** [comment]
Hi it doesn't pick up the device for example I get elan when I select show drivername on fingerprint GUI. Nothing when I build latest elan on your branch.

You are missing the vendor and product id for mine and the others you've added.
```
{.vendor = ELAN_VENDOR_ID, .product = 0x0c1a, .driver_data = ELAN_0C1A},
```

**Comment by iafilatov** [comment]
True, I forgot to add device ids. Fixed.

What do you mean harder? Does it error out or say 'stage not passed' or something like that? Could you post the logs please?

**Comment by iafilatov** [comment]
Just a guess but the calibration step has been reworked and that could cause your device to produce worse images somehow. Can you please try adding it to https://github.com/iafilatov/libfprint/blob/17cc36ed8a0ff5219b3b2b98abfe22e4bdb5dbc4/libfprint/drivers/elan.c#L443 and see if it helps?

**Comment by mikey0000** [comment]
alright I'll give it a go.

**Comment by mikey0000** [comment]
it seems when the room is too hot it won't work at all (which it used to). will verify tonight hopefully.

**Comment by iafilatov** [comment]
Oops, I'd made a typo that cause the driver to skip calibration on all devices... Fixed now.

**Comment by iafilatov** [comment]
Closing because the device is now recognized.

**Pull request closed without merging**
